image:
  file: .gitpod.Dockerfile
ports:
    - port: 3000
      onOpen: open-preview
      visibility: public
    - port: 3306
      onOpen: ignore
      visibility: public
    - port: 465
      onOpen: open-preview
tasks:
    - init: |
        cp .env.example .env &&
        pipenv install  &&
        mysql -u root -e "CREATE DATABASE example" &&
        pipenv run init &&
        pipenv run migrate &&
        pipenv run upgrade;
      command: >
        pipenv run start;
    - command: python3 welcome.py
      openMode: split-right

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: false
